export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESSS = 'REGISTER_USER_SUCCESSS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESSS = 'LOGIN_USER_SUCCESSS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESSS = 'SETUP_USER_SUCCESSS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESSS = 'UPDATE_USER_SUCCESSS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESSS = 'CREATE_JOB_SUCCESSS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const GET_JOB_BEGIN = 'GET_JOB_BEGIN'
export const GET_JOB_SUCCESSS = 'GET_JOB_SUCCESSS'

export const SETUP_EDIT_JOB = 'SETUP_EDIT_JOB'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESSS = 'EDIT_JOB_SUCCESSS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'